### ISSUE TITLE
code is inconsistent with your paper

### ISSUE THREAD

**Issue by pengzhangzhi** [luost26/diffab#5]
https://github.com/luost26/diffab/blob/6febe0243c67c1e21e7b418ea38e0c25eca42f04/diffab/modules/diffusion/transition.py#L98

Hi. In the forward diffusion process, given e_0, the initial rotations, this function generates the noised rotations by `R_noisy = E_scaled @ R0_scaled`. where E_scaled is sampled from a prior distribution. I wonder why `e_normal` is not used but declared? 
https://github.com/luost26/diffab/blob/6febe0243c67c1e21e7b418ea38e0c25eca42f04/diffab/modules/diffusion/transition.py#L112

In your paper, the `R_noisy` should be the interpolation between  `c0 * v_0`(scaled v_0) and `c1 * e_scaled`. But your code does not use c1 at all.

**Comment by luost26** [comment]
I named the variable `scaled` because `e_scaled` is already scaled by `c1`. The scaling factor `c1` is set as the std of the distribution.

https://github.com/luost26/diffab/blob/6febe0243c67c1e21e7b418ea38e0c25eca42f04/diffab/modules/diffusion/transition.py#L90

`e_normal` is for debugging. Just to check whether it comes back to a standard normal after division.

**Comment by pengzhangzhi** [comment]
My bad! Thank you soooo much.

**Comment by pengzhangzhi** [comment]
@luost26 , Hi. I have another question regarding the posterior formula of orientation 
![image](https://user-images.githubusercontent.com/59241275/206183552-b5ba0bcb-0a9d-448f-8fcb-bd46630d7ce4.png)

Why the mean of the posterior is the predicted O_0 instead of the interpolation between O_t and predicted O_0. The later one is more popular in Diffusion Model, including original DDPM.
